vim.g.mapleader = " "
vim.opt.termguicolors = true
vim.wo.number = true
-- vim.wo.relativenumber = true
vim.o.clipboard = "unnamedplus"
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.wrap = true
-- vim.opt.undodir = "~/.undodir"
