[FileDialog]
history=file:///home/devendra/Documents/UCAB/Gestion/Sesion 1, file:///home/devendra/Documents/UCAB/Gestion, file:///home/devendra/Documents/UCAB/Evaluacion/Caso de Estudio/Videos, file:///home/devendra/Desktop, file:///home/devendra/Documents/UCAB/Distribuidos/RMI, file:///home/devendra
lastVisited=file:///home/devendra
qtVersion=5.15.0
shortcuts=file:, file:///home/devendra
sidebarWidth=98
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xec\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xff\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
