#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 7 -xoffset 14 -yoffset -52 -line-padding 4 -columns 3 -width 40 -lines 10 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme
